backend:
  name: git-gateway

media_folder: static/images
public_folder: src/images

collections:
  - name: post
    label: post
    folder: posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: cover, label: Cover, widget: "image"}
      - { name: category, label: category}
      - { name: tags, label: tags}
      - { name: date, label: Date, widget: date }
      - { name: body, label: Body, widget: markdown }